name: spontaneous
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  supabase_auth_ui: ^0.5.1
  supabase_flutter: ^2.0.0
  fluttertoast: ^8.2.4
  envied: ^0.5.3 # Add this line

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  intl: ^0.19.0
  build_runner: ^2.4.12
  envied_generator: ^0.5.3 # Add this line

flutter:
  uses-material-design: true
  generate: false # Add this line
