// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0nQV4d83KtO0k-lCAJ1985BbOnE_MIio',
    appId: '1:628020005413:web:a3063a17593e73c3dacdcc',
    messagingSenderId: '628020005413',
    projectId: 'spontaneous-bsw',
    authDomain: 'spontaneous-bsw.firebaseapp.com',
    storageBucket: 'spontaneous-bsw.appspot.com',
    measurementId: 'G-MSWQ8CSK16',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQ041Uj3Bk84iU9xtOIyDJLyADV0HT0po',
    appId: '1:628020005413:android:8ecb2324376656d2dacdcc',
    messagingSenderId: '628020005413',
    projectId: 'spontaneous-bsw',
    storageBucket: 'spontaneous-bsw.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAP_iN0SUhVM47ltCQ5fDlyD6qTspHSuU4',
    appId: '1:628020005413:ios:41821a198778023bdacdcc',
    messagingSenderId: '628020005413',
    projectId: 'spontaneous-bsw',
    storageBucket: 'spontaneous-bsw.appspot.com',
    iosClientId: '628020005413-o8ja0fest6lvf37aic0uatm6q3i0enu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.spontaneous',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAP_iN0SUhVM47ltCQ5fDlyD6qTspHSuU4',
    appId: '1:628020005413:ios:41821a198778023bdacdcc',
    messagingSenderId: '628020005413',
    projectId: 'spontaneous-bsw',
    storageBucket: 'spontaneous-bsw.appspot.com',
    iosClientId: '628020005413-o8ja0fest6lvf37aic0uatm6q3i0enu6.apps.googleusercontent.com',
    iosBundleId: 'com.example.spontaneous',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0nQV4d83KtO0k-lCAJ1985BbOnE_MIio',
    appId: '1:628020005413:web:f5ef6c22af3385a0dacdcc',
    messagingSenderId: '628020005413',
    projectId: 'spontaneous-bsw',
    authDomain: 'spontaneous-bsw.firebaseapp.com',
    storageBucket: 'spontaneous-bsw.appspot.com',
    measurementId: 'G-74X18N05LG',
  );

}